CREATE OR REPLACE PROCEDURE    "DEVOLVER_PRESTAMO" (
	nprestamo IN NUMBER,

	nffin IN DATE
) IS

	finalizacion DATE;

BEGIN
	SELECT FPLAZO INTO finalizacion FROM PRESTAMOS WHERE PRESTAMOS.ID=nprestamo;

	UPDATE PRESTAMOS SET FFIN=nffin WHERE ID=nprestamo;

	UPDATE LIBROS SET DISPONIBLE=1 WHERE ID=(SELECT DEREF(LIBRO).ID FROM PRESTAMOS WHERE ID=nprestamo);

	IF nffin>finalizacion THEN

		UPDATE USUARIOS SET PENALIZACION=1 WHERE NCARNET=(SELECT DEREF(USUARIO).NCARNET FROM PRESTAMOS WHERE ID=nprestamo);

	END IF;
END;